#!/usr/bin/env python3
"""
categories_data.py

The canonical Tastecard category catalogue (consumed by generate_categories.py).
Each entry: name (display), rarity (0..1), and SigLIP detection prompts. Prompts are
short, concrete "a photo of X" phrases that are visually discriminative and DON'T
overlap with neighbouring categories. There is no tagline — the app no longer shows one.

Naming: catchy / social-media / in-group references where they land (e.g. drummers and
"Not Quite My Tempo"), so the people who relate to a category instantly get it.

Design rules:
- Things real people actually photograph — not bland filler.
- Distinct subjects: avoid pairs that fire on the same images. Where two ideas are close,
  the prompts pin different scenes.
- "A Slice Of My <Country> Side" gathers a cuisine's iconic dishes under one category.
- rarity: everyday subjects low (~0.1–0.3), deliberate hobbies mid (~0.35–0.6),
  genuinely uncommon subjects high (~0.6–0.95).
"""

from __future__ import annotations

# (name, rarity, [prompts])
CATEGORIES: list[tuple[str, float, list[str]]] = [
    # ---- People & everyday ----
    ("Main Character Energy", 0.12,
     ["a selfie of one person", "a close-up portrait of a face", "a mirror selfie"]),
    ("The Group Chat, In Person", 0.15,
     ["a group photo of friends together", "people socialising at a gathering", "a candid group of friends"]),
    ("My Favourite People", 0.2,
     ["a family gathering with multiple generations", "parents and children together", "a family portrait at home"]),
    ("Tiny Hands", 0.66,
     ["a newborn baby", "a parent holding a baby", "a baby's first photos"]),
    ("Small Humans, Big Energy", 0.4,
     ["young children playing", "kids at a playground", "a child playing with toys"]),
    ("Nothing Good After 2AM", 0.3,
     ["a party at night", "a nightclub scene", "people dancing at night"]),
    ("Last Drink, I Promise...", 0.22,
     ["a pint of beer", "a craft beer or pub interior", "people drinking beer at a bar"]),
    ("Happy Hour Hero", 0.35,
     ["a cocktail in a glass", "a bartender making a cocktail", "colourful cocktails on a bar"]),
    ("But First, Wine", 0.4,
     ["a glass of wine", "a bottle of wine on a table", "a vineyard or wine tasting"]),

    # ---- Coffee, tea & sweet drinks ----
    ("But First, Coffee", 0.12,
     ["a cup of coffee", "a latte with latte art", "the interior of a coffee shop"]),
    ("Matcha Made In Heaven", 0.3,
     ["a matcha latte", "a green matcha drink", "a cup of matcha tea"]),
    ("Boba Run", 0.28,
     ["a cup of bubble tea", "boba milk tea", "a bubble tea drink with tapioca pearls"]),
    ("Spill The Tea", 0.4,
     ["a teapot and teacup", "loose leaf tea being poured", "an afternoon tea spread"]),
    ("Just One Energy Drink Left", 0.35,
     ["a can of energy drink", "a Monster or Red Bull energy drink", "a fizzy soda can like coke or sprite"]),

    # ---- Food ----
    ("Eat First, Questions Later", 0.12,
     ["a plated meal at a restaurant", "a close-up photo of food", "a beautifully plated dish on a table"]),
    ("Bake It Till You Make It", 0.32,
     ["home-baked bread or cake", "a person baking in a kitchen", "a tray of cookies or pastries"]),
    ("Steak Your Claim", 0.24,
     ["a steak on a plate", "a grilled steak close-up", "a steak dinner"]),
    ("Certified Crispy", 0.26,
     ["fried chicken", "a plate of fried chicken", "chicken wings"]),
    ("Donut Worry, Be Happy", 0.26,
     ["a box of doughnuts", "a glazed doughnut close-up", "doughnuts on display"]),
    ("Drink Your Greens", 0.26,
     ["a green smoothie or juice", "a smoothie bowl", "a fresh pressed juice"]),
    ("It's RAW! (Gordon Voice)", 0.35,
     ["a plate of sushi", "sushi rolls and sashimi", "a sushi platter"]),
    ("Slurp Now, Talk Later", 0.35,
     ["a bowl of ramen", "a steaming bowl of noodle soup", "ramen with toppings"]),
    ("Two Hands Required", 0.22,
     ["a burger", "a cheeseburger and fries", "a gourmet burger close-up"]),
    ("Brunch So Hard", 0.25,
     ["a brunch spread", "pancakes or waffles with toppings", "eggs benedict on a plate"]),
    ("Dessert Is A Personality", 0.22,
     ["a dessert plate", "a slice of cake", "ice cream or gelato"]),
    ("Girl Dinner", 0.45,
     ["a charcuterie board", "a cheese board with crackers", "a grazing platter"]),
    ("Low And Slow", 0.4,
     ["a barbecue grill with food", "meat on a grill", "a backyard bbq"]),
    ("No Menu, No Problem", 0.38,
     ["street food at a market", "a food stall or food truck", "food being cooked on the street"]),
    ("That Girl Grocery Haul", 0.4,
     ["fresh produce at a farmers market", "a market stall of fruit and vegetables", "a basket of fresh vegetables"]),
    ("Restaurant Energy, Kitchen Prices", 0.3,
     ["a home cooked meal being prepared", "ingredients laid out for cooking", "a person cooking at a stove"]),

    # ---- World cuisines ("A Slice Of My <Country> Side") ----
    ("A Slice Of My Italian Side", 0.2,
     ["a pizza", "a plate of pasta", "lasagna", "risotto", "tiramisu"]),
    ("A Slice Of My Indian Side", 0.32,
     ["a curry dish", "an indian thali", "biryani rice", "naan bread", "samosas"]),
    ("A Slice Of My Chinese Side", 0.3,
     ["dim sum dumplings", "chinese stir fry", "peking duck", "a hot pot meal", "fried rice"]),
    ("A Slice Of My Korean Side", 0.4,
     ["a korean bbq grill", "bibimbap in a bowl", "kimchi side dishes", "tteokbokki rice cakes", "korean fried chicken"]),
    ("A Slice Of My Thai Side", 0.42,
     ["pad thai noodles", "a thai green curry", "tom yum soup", "mango sticky rice"]),
    ("A Slice Of My French Side", 0.4,
     ["a croissant and pastries", "a fresh baguette", "creme brulee", "escargot", "a french cheese plate"]),
    ("A Slice Of My Greek Side", 0.45,
     ["a greek gyro or souvlaki", "a greek salad with feta", "moussaka", "baklava dessert"]),
    ("A Slice Of My Nigerian Side", 0.6,
     ["a plate of jollof rice", "suya grilled meat skewers", "egusi soup with pounded yam", "fried plantain"]),
    ("A Slice Of My Egyptian Side", 0.7,
     ["a bowl of koshari", "ful medames beans", "falafel ta'ameya", "molokhia stew"]),
    ("A Slice Of My Austrian Side", 0.72,
     ["a wiener schnitzel", "sachertorte chocolate cake", "apple strudel"]),

    # ---- Pets & animals ----
    ("Cat Distribution System", 0.18,
     ["a pet cat", "a cat close-up", "a cat lounging at home"]),
    ("Who's A Good Boy?", 0.16,
     ["a pet dog", "a dog close-up", "a dog playing outside"]),
    ("Birdwatching Era", 0.5,
     ["a wild bird", "a bird perched on a branch", "birds in nature"]),
    ("Tank Life", 0.7,
     ["a home aquarium with fish", "tropical fish in a fish tank", "an aquarium close-up"]),
    ("Cold-Blooded, Warmly Loved", 0.7,
     ["a pet reptile", "a lizard or snake in a terrarium", "a gecko close-up"]),
    ("Fresh Air & Animal Noises", 0.55,
     ["farm animals in a field", "cows sheep or chickens on a farm", "a barn with livestock"]),
    ("On Safari", 0.75,
     ["wild animals on a safari", "an elephant or lion in the wild", "wildlife on a savanna"]),

    # ---- Sports & fitness ----
    ("Just One More Mile", 0.35,
     ["a person running outdoors", "a road race or marathon", "running shoes or a running track"]),
    ("We Go Jim", 0.3,
     ["a gym with weights", "a person lifting weights", "dumbbells and gym equipment"]),
    ("Namaslay", 0.35,
     ["a person doing yoga", "a yoga pose on a mat", "a yoga studio"]),
    ("The Beautiful Game", 0.35,
     ["a person playing football soccer", "a football pitch", "a person in a football kit with a ball"]),
    ("Ball Is Life", 0.35,
     ["a basketball court", "a person playing basketball", "a basketball hoop"]),
    ("New Balls, Please", 0.45,
     ["a tennis court", "a person playing tennis", "a tennis racket and ball"]),
    ("A Good Walk, Spoiled", 0.5,
     ["a golf course", "a person golfing", "a golf ball on a tee"]),
    ("Two Wheels, One Obsession", 0.38,
     ["a bicycle", "a person cycling outdoors", "a bike on a cycling route"]),
    ("Pretending To Be Tony Hawk", 0.45,
     ["a person skateboarding", "a skateboard at a skatepark", "a skateboarding trick"]),
    ("Float Like A Butterfly", 0.45,
     ["a boxing gym", "a person with boxing gloves", "a martial arts training session"]),
    ("Snow Chaser", 0.6,
     ["a person skiing or snowboarding", "a ski slope on a mountain", "skiers on fresh snow"]),
    ("Hang Ten", 0.6,
     ["a surfer riding a wave", "a person with a surfboard at the beach", "surfing in the ocean"]),
    ("Just Send It", 0.6,
     ["a person rock climbing", "indoor bouldering at a climbing gym", "a climber on a rock face"]),
    ("The One That Got Away", 0.5,
     ["a person fishing", "a fishing rod by the water", "a freshly caught fish"]),
    ("Built For The Rink", 0.62,
     ["a person ice skating", "an ice rink", "ice skates on the ice"]),
    ("Pool Shark", 0.5,
     ["a pool or billiards table", "a person playing pool", "a snooker table"]),
    ("Ping Pong Bros", 0.5,
     ["a table tennis game", "a person playing ping pong", "a table tennis paddle and ball"]),
    ("One Hundred And Eighty!", 0.5,
     ["a dartboard", "a person throwing darts", "a darts game in a pub"]),
    ("Rented Shoes, Real Pride", 0.5,
     ["a bowling alley", "a person bowling", "bowling pins and a ball"]),
    ("Hit The Apex", 0.68,
     ["a go-kart on a track", "a person karting", "a racing kart"]),
    ("Howzat!", 0.6,
     ["a cricket match", "a person batting in cricket", "a cricket pitch"]),

    # ---- Outdoors, travel & places ----
    ("Peak Bagger", 0.45,
     ["a mountain summit", "a scenic mountain peak view", "a person at the top of a mountain"]),
    ("Boots On, Signal Off", 0.4,
     ["a person hiking on a forest trail", "a hiking trail through the woods", "a backpacker on a nature trail"]),
    ("Beach Please", 0.18,
     ["a beach", "the ocean or sea", "a coastal seaside view"]),
    ("Always On The Next Flight", 0.4,
     ["a famous landmark or tourist site", "a travel photo in a foreign city", "luggage or an airport terminal", "an airplane in flight", "a jet aircraft on a runway", "a view from an airplane window"]),
    ("Chasing Golden Hour", 0.2,
     ["a sunset or sunrise", "a dramatic sky with clouds", "a colourful sky at golden hour"]),
    ("Stillness Over Water", 0.55,
     ["a calm lake at dusk", "a reflection on still water", "a quiet waterside evening"]),
    ("Concrete Jungle", 0.35,
     ["a city skyline at night", "skyscrapers lit up at night", "an aerial view of a city at night"]),
    ("Cobblestone Era", 0.4,
     ["a historic old town street", "cobblestone streets and old buildings", "european old town architecture"]),
    ("Touch Grass, Pro Edition", 0.7,
     ["a forest of tall trees", "a dense green woodland", "sunlight through a forest"]),
    ("Sand, Silence, Big Skies", 0.7,
     ["a sand desert with dunes", "a desert landscape", "dunes under a clear sky"]),
    ("Chasing Waterfalls", 0.7,
     ["a waterfall", "a cascading waterfall in nature", "a person near a large waterfall"]),
    ("Out Of Office, Literally", 0.7,
     ["a tent at a campsite", "a campfire at night", "camping in nature"]),
    ("Holy Ground", 0.5,
     ["a cathedral interior", "a church or temple", "ornate religious architecture"]),
    ("The Best Parts Are Underground", 0.72,
     ["inside a cave", "a cave with rock formations", "a person exploring a cave"]),
    ("All Aboard", 0.6,
     ["a train journey", "a scenic railway", "a train at a station"]),

    # ---- Sky & nature phenomena ----
    ("Eyes On The Skies", 0.62,
     ["a night sky full of stars", "the moon close-up", "a milky way landscape"]),
    ("Aurora Chaser", 0.92,
     ["a picture of the northern lights", "aurora borealis in the sky", "green lights over a night landscape"]),
    ("Driving Toward The Weather", 0.7,
     ["a dramatic storm cloud", "lightning in the sky", "a moody stormy landscape"]),
    ("In Full Bloom", 0.2,
     ["a close-up of flowers", "a garden full of blooming flowers", "a field of wildflowers"]),
    ("Petal Season", 0.6,
     ["cherry blossom trees in bloom", "pink blossom branches", "a path lined with blossom"]),
    ("Sweater Weather", 0.45,
     ["autumn leaves in fall colours", "a path covered in orange leaves", "trees with red and gold foliage"]),
    ("Plant Parent", 0.3,
     ["houseplants by a window", "a collection of potted plants indoors", "a person tending indoor plants"]),

    # ---- Music & performance ----
    ("Moshpit Energy", 0.45,
     ["a live concert", "a music festival stage with lights", "a crowd at a concert with stage lights"]),
    ("Festival Era", 0.4,
     ["a music festival crowd", "a festival stage outdoors", "people at an outdoor festival"]),
    ("Wonderwall, Anyone?", 0.4,
     ["a person playing guitar", "a guitar or musical instrument", "a band rehearsing"]),
    ("Piano Man", 0.55,
     ["a person playing a piano", "a grand piano", "piano keys close-up"]),
    ("Not Quite My Tempo", 0.6,
     ["a drum kit", "a person playing drums", "a drummer on stage"]),
    ("On The Ones And Twos", 0.6,
     ["a dj with turntables", "a dj mixing at a party", "dj decks and a mixer"]),
    ("Vinyl Era", 0.6,
     ["a vinyl record", "a record player turntable", "a collection of vinyl records"]),
    ("Grab The Mic", 0.52,
     ["a karaoke night", "a person singing into a microphone", "a comedy club stage"]),
    ("Theatre Kid Forever", 0.55,
     ["a theatre stage with performers", "a theatre auditorium", "a live stage play"]),

    # ---- Hobbies & making ----
    ("BookTok Made Me Buy It", 0.2,
     ["a book or books", "a bookshelf or bookstore", "a person reading a book"]),
    ("Measure Twice, Post Once", 0.6,
     ["a woodworking project", "tools and timber in a workshop", "a person building furniture"]),
    ("Everything Is Awesome", 0.45,
     ["a lego build", "a model kit", "a detailed model or figurine"]),
    ("En Passant! (Holy Hell)", 0.35,
     ["a chessboard", "people playing a board game", "tabletop games on a table"]),
    ("Not A Costume, A Calling", 0.65,
     ["a person in a cosplay costume", "a costume at a convention", "an elaborate dressed-up character"]),
    ("Blank Canvas, Full Heart", 0.5,
     ["a painting on a canvas", "a person painting with a brush", "an artist's palette and easel"]),
    ("Sketchbook Era", 0.45,
     ["a pencil sketch in a sketchbook", "a person drawing", "a detailed drawing on paper"]),
    ("Unleash Your Inner Ghost", 0.6,
     ["a pottery wheel with clay", "handmade ceramic pottery", "a person making pottery"]),
    ("Hooked On Yarn", 0.55,
     ["knitting or crochet with yarn", "a ball of yarn and needles", "a handmade knitted item"]),
    ("A Gallery You Carry", 0.55,
     ["a tattoo on skin", "a tattoo artist working", "a detailed tattoo close-up"]),
    ("A Thousand Pieces, Zero Rush", 0.5,
     ["a jigsaw puzzle in progress", "puzzle pieces on a table", "a completed jigsaw puzzle"]),
    ("Stan Lee Approved", 0.45,
     ["a comic book", "a marvel or dc comics character", "a comic book collection"]),
    ("Otaku!", 0.45,
     ["anime artwork", "an anime figure or poster", "an anime convention"]),
    ("Mint Condition Only", 0.5,
     ["trading cards", "a trading card collection", "people playing a trading card game"]),

    # ---- Tech & creative gear ----
    ("Day One Pre-Order", 0.4,
     ["new tech gadgets", "a new smartphone or device", "consumer electronics on a desk"]),
    ("Battlestation", 0.5,
     ["a computer desk setup with rgb lighting", "a gaming pc battlestation", "multiple monitors on a desk", "a modern pc setup"]),
    ("One More Game, I Swear", 0.3,
     ["a video game screenshot", "a gaming console setup", "a game controller"]),
    ("Insert Coin To Continue", 0.65,
     ["a retro arcade machine", "an arcade with game cabinets", "a classic arcade game screen"]),
    ("God's Eye View", 0.7,
     ["a drone aircraft", "an aerial drone photo from above", "a person flying a drone"]),
    ("Film Is Not Dead", 0.6,
     ["a film camera", "a vintage analog camera", "35mm film photographs"]),
    ("Behind The Lens", 0.45,
     ["a dslr or mirrorless camera", "a photographer with a camera and lens", "camera gear and lenses"]),
    ("Layer By Layer", 0.7,
     ["a 3d printer printing an object", "a 3d printed model", "a desktop 3d printer at work"]),

    # ---- Fashion, beauty & collections ----
    ("The Beat Is Beating", 0.35,
     ["a makeup look close-up", "makeup products and brushes", "a beauty makeup application"]),
    ("Glazed Donut Skin", 0.4,
     ["skincare products on a shelf", "a facial skincare routine", "a vanity of beauty products"]),
    ("Nailed It", 0.45,
     ["a manicure with nail art", "painted fingernails close-up", "a nail salon manicure"]),
    ("Fit Check", 0.3,
     ["an outfit of the day mirror photo", "a fashion outfit laid out", "a stylish full body outfit"]),
    ("One Man's Trash", 0.5,
     ["vintage clothing on a rack", "a thrift or vintage clothing store", "secondhand fashion finds"]),
    ("Don't Crease 'Em", 0.4,
     ["sneakers or trainers", "a collection of shoes on display", "a close-up of athletic shoes"]),
    ("Drip Check", 0.45,
     ["jewellery close-up", "rings and necklaces", "a jewellery collection"]),
    ("It's Not About The Time", 0.5,
     ["a wristwatch close-up", "a luxury watch", "a watch collection"]),
    ("Smell Goods", 0.45,
     ["a perfume bottle", "a fragrance collection", "a bottle of cologne"]),
    ("If You Know, You Know", 0.5,
     ["a designer handbag", "a luxury fashion item", "a high-end boutique"]),

    # ---- Vehicles ----
    ("Car Guy Things", 0.35,
     ["a car", "a sports car or classic car", "a car show or garage"]),
    ("Loud Pipes Save Lives", 0.55,
     ["a motorcycle", "a person riding a motorbike", "a parked motorbike"]),
    ("Sea Legs", 0.5,
     ["a sailboat or yacht", "a person on a boat", "a boat out on the water"]),
    ("Horse Girl Era", 0.62,
     ["a person horse riding", "a horse and rider", "an equestrian scene"]),
    ("Up, Up And Away", 0.85,
     ["a hot air balloon in the sky", "colourful hot air balloons", "a hot air balloon festival"]),
    ("Pavement Is Optional", 0.6,
     ["an off-road 4x4 vehicle", "a truck on a dirt trail", "an off-road adventure vehicle"]),

    # ---- Events & celebrations ----
    ("Cake, Candles, Chaos", 0.3,
     ["a birthday cake with candles", "a birthday party with balloons", "people celebrating a birthday"]),
    ("She Said Yes!", 0.8,
     ["an engagement ring on a hand", "a proposal moment", "a close-up of an engagement ring"]),
    ("Just Married", 0.7,
     ["a wedding ceremony", "a bride and groom", "a wedding celebration"]),
    ("We Did It!", 0.7,
     ["a graduation ceremony", "a person in a graduation cap and gown", "graduates throwing caps"]),
    ("Oohs And Aahs", 0.45,
     ["a fireworks display", "fireworks in the night sky", "a firework celebration"]),
    ("Most Wonderful Time", 0.4,
     ["christmas decorations and lights", "a decorated christmas tree", "festive holiday decorations"]),
    ("Spooky Season", 0.5,
     ["halloween decorations and pumpkins", "a carved jack-o-lantern", "people in halloween costumes"]),
    ("All The Fun Of The Fair", 0.5,
     ["a funfair or carnival at night", "a ferris wheel lit up", "fairground rides"]),

    # ---- Lifestyle, home & work ----
    ("Soft Life", 0.3,
     ["a cosy home interior", "a styled living room", "a warm interior with soft lighting"]),
    ("Ambience Is A Hobby", 0.4,
     ["lit candles", "a candle close-up with flame", "candles creating ambience"]),
    ("Always Fresh Flowers", 0.35,
     ["a bouquet of flowers in a vase", "fresh cut flowers on a table", "a floral arrangement indoors"]),
    ("We Got The Keys!", 0.6,
     ["a set of house keys held up", "an empty new home interior", "a sold sign outside a house"]),
    ("Tidy Space, Tidy Mind", 0.45,
     ["an organised and tidy room", "a clean minimalist home", "neatly arranged shelves"]),
    ("Locked In", 0.26,
     ["a laptop at a cafe", "a notebook and coffee on a desk", "a study desk setup"]),
    ("Library Arc", 0.35,
     ["a study desk with books and notes", "a person studying", "a library study session"]),
    ("Corporate Era", 0.4,
     ["an office workspace", "a business meeting", "a corporate office interior"]),
    ("Self Care Is Mandatory", 0.5,
     ["a spa setting", "a relaxing spa treatment", "a spa with candles and towels"]),
    ("Dear Diary", 0.4,
     ["a bullet journal or planner", "a handwritten journal with pens", "a decorated planner spread"]),

    # ---- Screens & memory ----
    ("One Piece Is Peak", 0.4,
     ["a screenshot of a manga panel", "a screenshot of a manga", "a photo of a manga", "manga page or manhwa page"]),
    ("Academic Weapon", 0.3,
     ["a photo of handwritten notes", "a photo of a whiteboard with notes", "a screenshot of academic content"]),

    # ---- Screen / cinema ----
    ("Trailers Are Non-Negotiable", 0.4,
     ["a cinema screen and seats", "popcorn at the movies", "a movie theatre interior"]),

    # ---- Indulgent extras ----
    ("Summer In A Cone", 0.25,
     ["an ice cream cone", "gelato in a cup", "soft serve ice cream"]),
    ("Gardener's World", 0.45,
     ["a vegetable garden", "a person gardening outdoors", "raised garden beds with plants"]),
    ("The House Always Wins", 0.7,
     ["a casino table with chips", "playing poker with cards and chips", "a roulette or casino game"]),
]
