#!/usr/bin/env python3
"""
categories_data.py

The canonical Tastecard category catalogue (consumed by generate_categories.py).
Each entry: name (display), tagline (the shareable hook), rarity (0..1), and SigLIP
detection prompts. Prompts are written as short, concrete "a photo of X" phrases that
are visually discriminative and DON'T overlap with neighbouring categories.

Design rules:
- Things real people actually photograph — not bland filler.
- Distinct subjects: avoid pairs that fire on the same images (e.g. one "cars"
  category, not three). Where two ideas are close, the prompts pin different scenes.
- rarity: everyday subjects low (~0.1–0.3), deliberate hobbies mid (~0.35–0.6),
  genuinely uncommon subjects high (~0.6–0.95).
"""

from __future__ import annotations

# (name, tagline, rarity, [prompts])
CATEGORIES: list[tuple[str, str, float, list[str]]] = [
    # ---- People & everyday ----
    ("Main Character", "The camera loves you, and you know it.", 0.12,
     ["a selfie of one person", "a close-up portrait of a face", "a mirror selfie"]),
    ("Your People", "You document the crew like a photojournalist.", 0.15,
     ["a group photo of friends together", "people socialising at a gathering", "a candid group of friends"]),
    ("Family Time", "The whole family, all in one frame.", 0.2,
     ["a family gathering with multiple generations", "parents and children together", "a family portrait at home"]),
    ("Tiny Hands", "A new favourite person arrived.", 0.66,
     ["a newborn baby", "a parent holding a baby", "a baby's first photos"]),
    ("Kids at Play", "Small humans, big energy.", 0.4,
     ["young children playing", "kids at a playground", "a child playing with toys"]),
    ("After Dark", "Your best stories start after 10pm.", 0.3,
     ["a party at night", "a nightclub scene", "people dancing at night"]),
    ("Last Round", "The pub is basically your second living room.", 0.22,
     ["a pint of beer", "a craft beer or pub interior", "people drinking beer at a bar"]),
    ("Cocktail Hour", "Shaken, photographed, then sipped.", 0.35,
     ["a cocktail in a glass", "a bartender making a cocktail", "colourful cocktails on a bar"]),
    ("Wine O'Clock", "Swirl, sniff, snap.", 0.4,
     ["a glass of wine", "a bottle of wine on a table", "a vineyard or wine tasting"]),

    # ---- Coffee, tea & sweet drinks ----
    ("Powered by Caffeine", "Your love language is a flat white.", 0.12,
     ["a cup of coffee", "a latte with latte art", "the interior of a coffee shop"]),
    ("Matcha Hour", "Green, frothy, non-negotiable.", 0.3,
     ["a matcha latte", "a green matcha drink", "a cup of matcha tea"]),
    ("Boba Run", "There's always a half-finished cup with a fat straw.", 0.28,
     ["a cup of bubble tea", "boba milk tea", "a bubble tea drink with tapioca pearls"]),
    ("Tea Ceremony", "Steeped, never rushed.", 0.4,
     ["a teapot and teacup", "loose leaf tea being poured", "an afternoon tea spread"]),

    # ---- Food ----
    ("Eats First, Questions Later", "The food gets photographed before the first bite.", 0.12,
     ["a plated meal at a restaurant", "a close-up photo of food", "a beautifully plated dish on a table"]),
    ("Rise and Bake", "Flour on the counter, joy in the oven.", 0.32,
     ["home-baked bread or cake", "a person baking in a kitchen", "a tray of cookies or pastries"]),
    ("Medium Rare", "You take your steak seriously.", 0.24,
     ["a steak on a plate", "a grilled steak close-up", "a steak dinner"]),
    ("Bird and Sauce", "The crispier the better.", 0.26,
     ["fried chicken", "a plate of fried chicken", "chicken wings"]),
    ("Glaze Days", "A dozen is a serving size.", 0.26,
     ["a box of doughnuts", "a glazed doughnut close-up", "doughnuts on display"]),
    ("Green Juice", "Health, but make it photogenic.", 0.26,
     ["a green smoothie or juice", "a smoothie bowl", "a fresh pressed juice"]),
    ("Slice of Life", "Folded, never forked.", 0.18,
     ["a pizza", "a slice of pizza", "a whole pizza on a table"]),
    ("Sushi Hour", "Raw talent.", 0.35,
     ["a plate of sushi", "sushi rolls and sashimi", "a sushi platter"]),
    ("Ramen Run", "Slurp now, talk later.", 0.35,
     ["a bowl of ramen", "a steaming bowl of noodle soup", "ramen with toppings"]),
    ("Taco 'Bout It", "Folded happiness.", 0.32,
     ["tacos on a plate", "mexican street tacos", "a taco close-up"]),
    ("Burger Joint", "Two hands required.", 0.22,
     ["a burger", "a cheeseburger and fries", "a gourmet burger close-up"]),
    ("Brunch Club", "Late mornings, runny yolks.", 0.25,
     ["a brunch spread", "pancakes or waffles with toppings", "eggs benedict on a plate"]),
    ("Sweet Tooth", "Dessert is a personality trait.", 0.22,
     ["a dessert plate", "a slice of cake", "ice cream or gelato"]),
    ("Spice Route", "The hotter the better.", 0.35,
     ["a curry dish", "an indian thali", "a bowl of curry with rice"]),
    ("Cheese & Charcuterie", "A grazing board is a love letter.", 0.45,
     ["a charcuterie board", "a cheese board with crackers", "a grazing platter"]),
    ("Fire and Smoke", "Low and slow is a lifestyle.", 0.4,
     ["a barbecue grill with food", "meat on a grill", "a backyard bbq"]),
    ("Street Eats", "The best meals have no menu.", 0.38,
     ["street food at a market", "a food stall or food truck", "food being cooked on the street"]),
    ("Farmers Market", "You shop with a tote and a plan.", 0.4,
     ["fresh produce at a farmers market", "a market stall of fruit and vegetables", "a basket of fresh vegetables"]),
    ("Home Chef", "Restaurant energy, kitchen prices.", 0.3,
     ["a home cooked meal being prepared", "ingredients laid out for cooking", "a person cooking at a stove"]),

    # ---- Pets & animals ----
    ("Paws & Claws", "Ruled by a creature who ignores you.", 0.18,
     ["a pet cat", "a cat close-up", "a cat lounging at home"]),
    ("Good Boy", "Your phone is 40% this dog.", 0.16,
     ["a pet dog", "a dog close-up", "a dog playing outside"]),
    ("Feathered Friends", "You stop for every bird.", 0.5,
     ["a wild bird", "a bird perched on a branch", "birds in nature"]),
    ("Tank Life", "A whole world behind glass.", 0.6,
     ["a home aquarium with fish", "tropical fish in a fish tank", "an aquarium close-up"]),
    ("Scales & Tails", "Cold-blooded, warmly loved.", 0.7,
     ["a pet reptile", "a lizard or snake in a terrarium", "a gecko close-up"]),
    ("Farmyard", "Fresh air and animal noises.", 0.55,
     ["farm animals in a field", "cows sheep or chickens on a farm", "a barn with livestock"]),
    ("On Safari", "You came for the wildlife.", 0.75,
     ["wild animals on a safari", "an elephant or lion in the wild", "wildlife on a savanna"]),

    # ---- Sports & fitness ----
    ("Always on the Run", "Your camera roll has logged more miles than most people's cars.", 0.35,
     ["a person running outdoors", "a road race or marathon", "running shoes or a running track"]),
    ("Iron Paradise", "The gym is your second home.", 0.3,
     ["a gym with weights", "a person lifting weights", "dumbbells and gym equipment"]),
    ("Flow State", "Breathe in, bend, repeat.", 0.35,
     ["a person doing yoga", "a yoga pose on a mat", "a yoga studio"]),
    ("On the Pitch", "Weekends are measured in 90-minute halves.", 0.35,
     ["a person playing football soccer", "a football pitch", "a person in a football kit with a ball"]),
    ("Hoop Dreams", "The court is where you think clearest.", 0.35,
     ["a basketball court", "a person playing basketball", "a basketball hoop"]),
    ("Court Vision", "Love means nothing here.", 0.45,
     ["a tennis court", "a person playing tennis", "a tennis racket and ball"]),
    ("Tee Time", "Four hours of walking and one good shot.", 0.5,
     ["a golf course", "a person golfing", "a golf ball on a tee"]),
    ("Two Wheels", "Happiest somewhere between point A and point B.", 0.38,
     ["a bicycle", "a person cycling outdoors", "a bike on a cycling route"]),
    ("Board Feet", "Bruises heal, the clip lives forever.", 0.45,
     ["a person skateboarding", "a skateboard at a skatepark", "a skateboarding trick"]),
    ("Glove Up", "Stress has nowhere to hide.", 0.45,
     ["a boxing gym", "a person with boxing gloves", "a martial arts training session"]),
    ("Powder Days", "You chase the snow.", 0.6,
     ["a person skiing or snowboarding", "a ski slope on a mountain", "skiers on fresh snow"]),
    ("Surf's Up", "Dawn patrol, every time.", 0.6,
     ["a surfer riding a wave", "a person with a surfboard at the beach", "surfing in the ocean"]),
    ("Send It", "Chalk up, look up, climb.", 0.6,
     ["a person rock climbing", "indoor bouldering at a climbing gym", "a climber on a rock face"]),
    ("Gone Fishing", "Patience with a rod.", 0.5,
     ["a person fishing", "a fishing rod by the water", "a freshly caught fish"]),
    ("Fresh Ice", "Born for the rink.", 0.62,
     ["a person ice skating", "an ice rink", "ice skates on the ice"]),
    ("On the Baize", "You call your shots.", 0.5,
     ["a pool or billiards table", "a person playing pool", "a snooker table"]),
    ("Net Result", "Fast hands, faster trash talk.", 0.5,
     ["a table tennis game", "a person playing ping pong", "a table tennis paddle and ball"]),
    ("Bullseye", "Steady hand, sharp eye.", 0.5,
     ["a dartboard", "a person throwing darts", "a darts game in a pub"]),
    ("Strike Zone", "Rent the shoes, keep the pride.", 0.5,
     ["a bowling alley", "a person bowling", "bowling pins and a ball"]),
    ("Apex Hunter", "You take corners for fun.", 0.68,
     ["a go-kart on a track", "a person karting", "a racing kart"]),
    ("Howzat", "Tea breaks and long innings.", 0.6,
     ["a cricket match", "a person batting in cricket", "a cricket pitch"]),

    # ---- Outdoors, travel & places ----
    ("Summit Chaser", "You measure a good day in elevation gained.", 0.45,
     ["a mountain summit", "a scenic mountain peak view", "a person at the top of a mountain"]),
    ("Trailblazer", "Boots on, signal off.", 0.4,
     ["a person hiking on a forest trail", "a hiking trail through the woods", "a backpacker on a nature trail"]),
    ("Salt in the Air", "You gravitate to wherever water meets sand.", 0.18,
     ["a beach", "the ocean or sea", "a coastal seaside view"]),
    ("Wheels Up", "Your phone storage is mostly other time zones.", 0.3,
     ["a famous landmark or tourist site", "a travel photo in a foreign city", "luggage or an airport terminal"]),
    ("Golden Hour Loyalist", "You stop everything when the light goes gold.", 0.2,
     ["a sunset or sunrise", "a dramatic sky with clouds", "a colourful sky at golden hour"]),
    ("Last Light", "Stillness over water, every time.", 0.55,
     ["a calm lake at dusk", "a reflection on still water", "a quiet waterside evening"]),
    ("City Lights", "The skyline is your screensaver.", 0.35,
     ["a city skyline at night", "skyscrapers lit up at night", "an aerial view of a city at night"]),
    ("Old Town", "You photograph every cobblestone.", 0.4,
     ["a historic old town street", "cobblestone streets and old buildings", "european old town architecture"]),
    ("Into the Wild", "Trees, trails and zero bars.", 0.4,
     ["a forest of tall trees", "a dense green woodland", "sunlight through a forest"]),
    ("Desert Lines", "Sand, silence, and big skies.", 0.7,
     ["a sand desert with dunes", "a desert landscape", "dunes under a clear sky"]),
    ("Chasing Waterfalls", "You'll hike for the roar.", 0.6,
     ["a waterfall", "a cascading waterfall in nature", "a person near a large waterfall"]),
    ("Under Canvas", "Home is wherever the tent is.", 0.5,
     ["a tent at a campsite", "a campfire at night", "camping in nature"]),
    ("Holy Ground", "Awe finds you in quiet places.", 0.5,
     ["a cathedral interior", "a church or temple", "ornate religious architecture"]),
    ("Cave Dweller", "The best parts are underground.", 0.72,
     ["inside a cave", "a cave with rock formations", "a person exploring a cave"]),
    ("Steam Engine", "The journey beats the destination.", 0.6,
     ["a train journey", "a scenic railway", "a train at a station"]),
    ("Plane Spotter", "You look up when others look down.", 0.6,
     ["an airplane in flight", "a jet aircraft on a runway", "a view from an airplane window"]),

    # ---- Sky & nature phenomena ----
    ("Star Gazer", "You point the camera up.", 0.62,
     ["a night sky full of stars", "the moon close-up", "a milky way landscape"]),
    ("Aurora Chaser", "You'd freeze for that sky.", 0.92,
     ["the northern lights", "aurora borealis in the sky", "green lights over a night landscape"]),
    ("Storm Watcher", "You drive toward the weather.", 0.7,
     ["a dramatic storm cloud", "lightning in the sky", "a moody stormy landscape"]),
    ("In Bloom", "You can't walk past a flower.", 0.2,
     ["a close-up of flowers", "a garden full of blooming flowers", "a field of wildflowers"]),
    ("Petal Season", "Spring stops you in your tracks.", 0.6,
     ["cherry blossom trees in bloom", "pink blossom branches", "a path lined with blossom"]),
    ("Falling Leaves", "You live for sweater weather.", 0.45,
     ["autumn leaves in fall colours", "a path covered in orange leaves", "trees with red and gold foliage"]),
    ("Plant Parent", "Your windowsill is a jungle.", 0.3,
     ["houseplants by a window", "a collection of potted plants indoors", "a person tending indoor plants"]),

    # ---- Music & performance ----
    ("Front Row Energy", "A graveyard of blurry stage photos and zero regrets.", 0.35,
     ["a live concert", "a music festival stage with lights", "a crowd at a concert with stage lights"]),
    ("Crowd Surfer", "Mud, lights, and zero regrets.", 0.4,
     ["a music festival crowd", "a festival stage outdoors", "people at an outdoor festival"]),
    ("Six Strings", "There's always an instrument within reach.", 0.4,
     ["a person playing guitar", "a guitar or musical instrument", "a band rehearsing"]),
    ("Eighty-Eight Keys", "You'll find the nearest piano.", 0.55,
     ["a person playing a piano", "a grand piano", "piano keys close-up"]),
    ("Keep the Beat", "Loud is the point.", 0.6,
     ["a drum kit", "a person playing drums", "a drummer on stage"]),
    ("On the Decks", "You read the room through a mixer.", 0.6,
     ["a dj with turntables", "a dj mixing at a party", "dj decks and a mixer"]),
    ("Crate Digger", "The hiss is part of the charm.", 0.6,
     ["a vinyl record", "a record player turntable", "a collection of vinyl records"]),
    ("Mic Night", "You'll grab the mic without being asked.", 0.52,
     ["a karaoke night", "a person singing into a microphone", "a comedy club stage"]),
    ("Curtain Call", "You clap loudest at the bows.", 0.55,
     ["a theatre stage with performers", "a theatre auditorium", "a live stage play"]),

    # ---- Hobbies & making ----
    ("One More Chapter", "There's always a current read in the camera roll.", 0.2,
     ["a book or books", "a bookshelf or bookstore", "a person reading a book"]),
    ("Sawdust", "Measure twice, post once.", 0.6,
     ["a woodworking project", "tools and timber in a workshop", "a person building furniture"]),
    ("Brick by Brick", "Some builds take all weekend, and that's the point.", 0.45,
     ["a lego build", "a model kit", "a detailed model or figurine"]),
    ("Your Move", "The board comes out and the night's decided.", 0.35,
     ["a chessboard", "people playing a board game", "tabletop games on a table"]),
    ("In Character", "You don't dress up, you transform.", 0.65,
     ["a person in a cosplay costume", "a costume at a convention", "an elaborate dressed-up character"]),
    ("Brush Strokes", "Blank canvas, full heart.", 0.5,
     ["a painting on a canvas", "a person painting with a brush", "an artist's palette and easel"]),
    ("Sketchbook", "You think in pencil.", 0.45,
     ["a pencil sketch in a sketchbook", "a person drawing", "a detailed drawing on paper"]),
    ("Throwing Clay", "Mud, wheel, magic.", 0.6,
     ["a pottery wheel with clay", "handmade ceramic pottery", "a person making pottery"]),
    ("Yarn Over", "Slow stitches, warm results.", 0.55,
     ["knitting or crochet with yarn", "a ball of yarn and needles", "a handmade knitted item"]),
    ("Inked Skin", "A gallery you carry with you.", 0.55,
     ["a tattoo on skin", "a tattoo artist working", "a detailed tattoo close-up"]),
    ("Puzzle Mode", "A thousand pieces, zero rush.", 0.5,
     ["a jigsaw puzzle in progress", "puzzle pieces on a table", "a completed jigsaw puzzle"]),
    ("Inked Pages", "A shelf you'll never thin out.", 0.45,
     ["a comic book", "manga pages", "a comic book collection"]),
    ("Anime Heart", "A whole world in every frame.", 0.45,
     ["anime artwork", "an anime figure or poster", "an anime convention"]),
    ("Deck Builder", "The collection is never finished.", 0.5,
     ["trading cards", "a trading card collection", "people playing a trading card game"]),

    # ---- Tech & creative gear ----
    ("Tech Forward", "First in line, every launch.", 0.4,
     ["new tech gadgets", "a new smartphone or device", "consumer electronics on a desk"]),
    ("Battlestation", "Cable management is self-care.", 0.5,
     ["a computer desk setup with rgb lighting", "a gaming pc battlestation", "multiple monitors on a desk"]),
    ("Player One", "Your screenshots have a high score.", 0.3,
     ["a video game screenshot", "a gaming console setup", "a game controller"]),
    ("Arcade Days", "Insert coin to continue.", 0.65,
     ["a retro arcade machine", "an arcade with game cabinets", "a classic arcade game screen"]),
    ("Drone Pilot", "You see the world from above.", 0.7,
     ["a drone aircraft", "an aerial drone photo from above", "a person flying a drone"]),
    ("Lens Hunter", "Digital's fine, but film has soul.", 0.6,
     ["a film camera", "a vintage analog camera", "35mm film photographs"]),
    ("Through the Viewfinder", "You frame the world for a living, or might as well.", 0.45,
     ["a dslr or mirrorless camera", "a photographer with a camera and lens", "camera gear and lenses"]),
    ("Maker Mode", "Layer by layer, idea to object.", 0.7,
     ["a 3d printer printing an object", "a 3d printed model", "a desktop 3d printer at work"]),

    # ---- Fashion, beauty & collections ----
    ("Beat Face", "Your face is the canvas.", 0.35,
     ["a makeup look close-up", "makeup products and brushes", "a beauty makeup application"]),
    ("Skin First", "Glow is a long game and you're winning it.", 0.4,
     ["skincare products on a shelf", "a facial skincare routine", "a vanity of beauty products"]),
    ("Nailed It", "Your hands are the accessory.", 0.45,
     ["a manicure with nail art", "painted fingernails close-up", "a nail salon manicure"]),
    ("Fit Check", "The mirror gets a daily feature.", 0.3,
     ["an outfit of the day mirror photo", "a fashion outfit laid out", "a stylish full body outfit"]),
    ("Thrift Finds", "One person's closet clear-out is your jackpot.", 0.5,
     ["vintage clothing on a rack", "a thrift or vintage clothing store", "secondhand fashion finds"]),
    ("Sole Collector", "Boxes you'll never throw away.", 0.4,
     ["sneakers or trainers", "a collection of shoes on display", "a close-up of athletic shoes"]),
    ("Layered Up", "The right piece finishes everything.", 0.45,
     ["jewellery close-up", "rings and necklaces", "a jewellery collection"]),
    ("Time Piece", "It's never just about telling the time.", 0.5,
     ["a wristwatch close-up", "a luxury watch", "a watch collection"]),
    ("Signature Scent", "You're remembered by how you smelled.", 0.45,
     ["a perfume bottle", "a fragrance collection", "a bottle of cologne"]),
    ("Designer Eye", "You know quality on sight.", 0.5,
     ["a designer handbag", "a luxury fashion item", "a high-end boutique"]),

    # ---- Vehicles ----
    ("Engine Heart", "You'd photograph a parked car you'll never own.", 0.35,
     ["a car", "a sports car or classic car", "a car show or garage"]),
    ("Full Throttle", "Two wheels, one obsession.", 0.55,
     ["a motorcycle", "a person riding a motorbike", "a parked motorbike"]),
    ("Sea Legs", "Land is fine, but the water's better.", 0.5,
     ["a sailboat or yacht", "a person on a boat", "a boat out on the water"]),
    ("In the Saddle", "Reins in hand, head clear.", 0.62,
     ["a person horse riding", "a horse and rider", "an equestrian scene"]),
    ("Up and Away", "The best views need a basket.", 0.85,
     ["a hot air balloon in the sky", "colourful hot air balloons", "a hot air balloon festival"]),
    ("Off the Grid", "Pavement is optional.", 0.6,
     ["an off-road 4x4 vehicle", "a truck on a dirt trail", "an off-road adventure vehicle"]),

    # ---- Events & celebrations ----
    ("Make a Wish", "Cake, candles, chaos.", 0.3,
     ["a birthday cake with candles", "a birthday party with balloons", "people celebrating a birthday"]),
    ("She Said Yes", "A yes worth photographing forever.", 0.8,
     ["an engagement ring on a hand", "a proposal moment", "a close-up of an engagement ring"]),
    ("Just Married", "The big day, frame by frame.", 0.7,
     ["a wedding ceremony", "a bride and groom", "a wedding celebration"]),
    ("Cap and Gown", "You earned the tassel.", 0.7,
     ["a graduation ceremony", "a person in a graduation cap and gown", "graduates throwing caps"]),
    ("Lights Up", "You'll stand in the cold for a good display.", 0.45,
     ["a fireworks display", "fireworks in the night sky", "a firework celebration"]),
    ("Season's Greetings", "You go all out in December.", 0.4,
     ["christmas decorations and lights", "a decorated christmas tree", "festive holiday decorations"]),
    ("Spooky Season", "October is a whole personality.", 0.5,
     ["halloween decorations and pumpkins", "a carved jack-o-lantern", "people in halloween costumes"]),
    ("All the Fun of the Fair", "Lights, rides, and questionable hot dogs.", 0.5,
     ["a funfair or carnival at night", "a ferris wheel lit up", "fairground rides"]),

    # ---- Lifestyle, home & work ----
    ("Cosy Corner", "Soft light, softer evenings.", 0.3,
     ["a cosy home interior", "a styled living room", "a warm interior with soft lighting"]),
    ("Candle Glow", "Ambience is a hobby.", 0.4,
     ["lit candles", "a candle close-up with flame", "candles creating ambience"]),
    ("Fresh Cut", "There are always flowers on the table.", 0.35,
     ["a bouquet of flowers in a vase", "fresh cut flowers on a table", "a floral arrangement indoors"]),
    ("New Keys", "New keys, new chapter.", 0.6,
     ["a set of house keys held up", "an empty new home interior", "a sold sign outside a house"]),
    ("Sunday Reset", "Tidy space, tidy mind.", 0.45,
     ["an organised and tidy room", "a clean minimalist home", "neatly arranged shelves"]),
    ("Page and Pour", "Productive, but make it aesthetic.", 0.26,
     ["a laptop at a cafe", "a notebook and coffee on a desk", "a study desk setup"]),
    ("Study Grind", "Deadlines build character.", 0.35,
     ["a study desk with books and notes", "a person studying", "a library study session"]),
    ("Nine to Five", "The grind, documented.", 0.4,
     ["an office workspace", "a business meeting", "a corporate office interior"]),
    ("Self Care Sunday", "You booked the appointment.", 0.5,
     ["a spa setting", "a relaxing spa treatment", "a spa with candles and towels"]),
    ("Dear Diary", "Your thoughts deserve nice paper.", 0.4,
     ["a bullet journal or planner", "a handwritten journal with pens", "a decorated planner spread"]),

    # ---- Screens & memory ----
    ("Caption Material", "Half your gallery is things you meant to send.", 0.3,
     ["a meme screenshot", "a funny social media post screenshot", "a screenshot of a funny message"]),
    ("Note to Self", "Your camera is basically your memory.", 0.3,
     ["a photo of handwritten notes", "a photo of a whiteboard with notes", "a screenshot of a note or list"]),

    # ---- Screen / cinema ----
    ("Big Screen", "Trailers are non-negotiable.", 0.4,
     ["a cinema screen and seats", "popcorn at the movies", "a movie theatre interior"]),

    # ---- Indulgent extras ----
    ("Ice Cream Dreams", "Summer in a cone.", 0.25,
     ["an ice cream cone", "gelato in a cup", "soft serve ice cream"]),
    ("Gardener's World", "Dirt under the nails, joy in the rows.", 0.45,
     ["a vegetable garden", "a person gardening outdoors", "raised garden beds with plants"]),
    ("High Roller", "The felt is calling.", 0.7,
     ["a casino table with chips", "playing poker with cards and chips", "a roulette or casino game"]),
]
